# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-04 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fav_by',
            field=models.ManyToManyField(related_name='favoriteitems', to='wish_items.User'),
        ),
    ]
